export * from './addArticlePage';
export * from './addCommentPage';
export * from './articlePage';
export * from './changePasswordPage';
export * from './loginPage';
export * from './mainPage';
export * from './registerPage';
export * from './settingsPage';
export * from './yourfeedPage';